version: '3.5'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app_web/flask_app/static:/app/static
      - ./app-upload:/app/static/upload
    depends_on:
      - app

  app:
    build: app_web
    volumes:
      - ./app-data:/app/flask_app/data
      - ./app-upload:/app/flask_app/static/upload

  cron:
    build: app_azure
    restart: always
    volumes:
      - ./app-data:/app/data
      - ./app-upload:/app/upload

# ===== nginx
# docker run --rm nginx cat /etc/nginx/nginx.conf > nginx/nginx.conf

# docker-compose up -d nginx
# docker-compose exec nginx nginx -s reload
